CREATE SEQUENCE SEQ_NumSpectacle 
INCREMENT BY 1
START WITH 1
MAXVALUE 999;

CREATE SEQUENCE SEQ_NumClient
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEQ_NumBillet
INCREMENT BY 1
START WITH 1
MAXVALUE 9999;

CREATE SEQUENCE SEQ_NumSalle
INCREMENT BY 1
START WITH 1
MAXVALUE 99;

CREATE SEQUENCE SEQ_NumSection
INCREMENT BY 1
START WITH 1
MAXVALUE 99;

CREATE SEQUENCE SEQ_FACTURE
INCREMENT BY 1
START WITH 1
MAXVALUE 99999;

CREATE SEQUENCE SEQ_CATEGORIE
INCREMENT BY 1
START WITH 1
MAXVALUE 99;
